#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Generate src/core/qgsunaccent_generated_rules.cpp from resources/unaccent.rules.

Implements full PostgreSQL unaccent.rules behaviour:

- Rule formats:
      SRC DST
      SRC
      SRC ""
      SRC "quoted""value"

- If DST is missing → delete SRC (DST = "")
- Quoted DST strings decode internal "" → "
"""

from pathlib import Path
import re
import sys

ROOT = Path(__file__).resolve().parent.parent
RULES_FILE = ROOT / "resources" / "unaccent.rules"
OUT_FILE = ROOT / "src" / "core" / "qgsunaccent_generated_rules.cpp"


def decode_quoted(dst: str) -> str:
    """
    PostgreSQL unaccent quoted-string rules:
      - Surrounding quotes removed
      - Inside: "" → "
    """
    inner = dst[1:-1]
    result = []

    i = 0
    n = len(inner)
    while i < n:
        ch = inner[i]
        if ch == '"' and i + 1 < n and inner[i + 1] == '"':
            result.append('"')
            i += 2
        else:
            result.append(ch)
            i += 1

    return "".join(result)


def parse_rules(path: Path):
    rules = []

    with path.open(encoding="utf-8") as f:
        for lineno, raw in enumerate(f, 1):
            line = raw.strip()

            if not line or line.startswith("#"):
                continue

            parts = line.split()

            # Only a source token, empty it
            if len(parts) == 1:
                src = parts[0]
                dst = ""
                rules.append((src, dst))
                continue

            # Source + destination
            src = parts[0]
            dst_raw = " ".join(parts[1:])

            # Handle quoted DST
            if dst_raw.startswith('"') and dst_raw.endswith('"') and len(dst_raw) >= 2:
                dst = decode_quoted(dst_raw)
            else:
                dst = dst_raw

            rules.append((src, dst))

    return rules


def cpp_escape(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"')


def write_cpp(path: Path, rules):
    with path.open("w", encoding="utf-8", newline="\n") as f:
        f.write(
            "/*\n"
            " * AUTO-GENERATED FILE - DO NOT EDIT\n"
            " * Generated by scripts/generate_unaccent_rules.py\n"
            " * from resources/unaccent.rules\n"
            " */\n\n"
        )

        f.write('#include "qgsstringutils.h"\n\n')
        f.write("#include <QHash>\n")
        f.write("#include <QString>\n\n")

        f.write("QHash<QString, QString> QgsStringUtils::createUnaccentMap()\n")
        f.write("{\n")
        f.write("  QHash<QString, QString> map;\n\n")

        for src, dst in rules:
            esc_src = cpp_escape(src)

            if dst == "":
                f.write(
                    f'  map.insert( QStringLiteral( "{esc_src}" ), QString() );\n'
                )
            else:
                esc_dst = cpp_escape(dst)
                f.write(
                    f'  map.insert( QStringLiteral( "{esc_src}" ), '
                    f'QStringLiteral( "{esc_dst}" ) );\n'
                )

        f.write("\n  return map;\n")
        f.write("}\n")


def main():
    if not RULES_FILE.exists():
        print(f"ERROR: rules file not found: {RULES_FILE}", file=sys.stderr)
        sys.exit(1)

    rules = parse_rules(RULES_FILE)
    write_cpp(OUT_FILE, rules)

    print(f"✓ Generated: {OUT_FILE}")
    print(f"✓ Total rules: {len(rules)}")


if __name__ == "__main__":
    main()
